### ISSUE TITLE
建议：加上注释、巴利语对照——随喜赞叹贤友对正法的护持🙏

### ISSUE THREAD

**Issue by Jason4V** [sutra-mobi/nikaya#1]
庄老师官网，翻译都有对很多重点词句的注释，同时也有巴利语对照。 
当然北大、杭佛版本也都有注释，希望能同步过来，方便查阅与学习。谢谢贤友😄  Sādhu 🙏  @sutra-mobi

**Comment by sutra-mobi** [comment]
> 庄老师官网，翻译都有对很多重点词句的注释，同时也有巴利语对照。
> 当然北大、杭佛版本也都有注释，希望能同步过来，方便查阅与学习。谢谢贤友😄 Sādhu 🙏 @sutra-mobi

杭州佛学院版我所见到的只有正文没有任何注释，您提到的另外两个版本的相关注释今后时间允许的话会逐渐完善，欢迎提供更多建议。

**Comment by sikaco** [comment]
Sādhu🙏，愿法喜充满，功德无量。

**Comment by Jason4V** [comment]
> 杭州佛学院版我所见到的只有正文没有任何注释，您提到的另外两个版本的相关注释今后时间允许的话会逐渐完善，欢迎提供更多建议。

许久不见，发现已经北大和杭佛版本已经加入了！太赞了贤友～
期待后期注释也能加入的一天！界面和交互可以参考  https://suttacentral.net/mn2/en/sujato#4.1

![1](https://user-images.githubusercontent.com/385914/117747514-e5eb8280-b240-11eb-80b4-429aa2822dba.png)

**Comment by sutra-mobi** [comment]
> > 杭州佛学院版我所见到的只有正文没有任何注释，您提到的另外两个版本的相关注释今后时间允许的话会逐渐完善，欢迎提供更多建议。
> 
> 许久不见，发现已经北大和杭佛版本已经加入了！太赞了贤友～
> 期待后期注释也能加入的一天！界面和交互可以参考 https://suttacentral.net/mn2/en/sujato#4.1
> 
> ![1](https://user-images.githubusercontent.com/385914/117747514-e5eb8280-b240-11eb-80b4-429aa2822dba.png)

精力有限，有时间的话会慢慢的完善，感谢关注。
关于界面，我的本意是提供一种干净的“纯”文本格式，不添加太多格式信息，而Markdown是一种相对好的表现形式。
通过gitbook-cli等类似的工具可以生成简洁的web页面，也可以很方便的生成pdf和mobi格式方便在pad、kindle等移动设备上阅读。

**Comment by XHBBKMP** [comment]
贤友，请警惕这样的行为是否违背了五戒中的偷盗戒
